dispatcher:
  polling:
    timeout: PT2M
  dispatch:
    root: http://localhost:8080
    initDelay: PT30S
    interval: PT30S

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://postgres/train_handler
    username: postgres
    password: password
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    operationsSorter: alpha

management:
  health:
    solr:
      enabled:  false
  info:
    defaults:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, info
