name: "Security Audit"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop ]
  schedule:
    - cron: '23 4 * * 1'

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    env:
      JAVA_DISTRIBUTION: microsoft
      JAVA_VERSION: 17

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow

      # (1) -> Prepare cache
      - name: Cache ~/.m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.JAVA_VERSION }}-maven-${{ hashFiles('**/pom.xml') }}

      # (2) -> Prepare Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Verify Maven and Java
        run: |
          mvn --version

      # (3) -> Init CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'java'

      # (3) -> Build
      - name: Build package
        run: |
          mvn --quiet -B -U --fail-fast -DskipTests package

      # (4) -> CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  snyk:
    name: Snyk (Maven)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Perform Snyk Check (Maven)
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  snyk-docker:
    name: Snyk (Docker)
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    env:
      PUBLIC_IMAGE: fairdata/trainhandler-server
      TAG_DEVELOP: develop

    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Docker build
        run: |
          docker pull $PUBLIC_IMAGE:$TAG_DEVELOP
          docker build --cache-from $PUBLIC_IMAGE:$TAG_DEVELOP -t fdp:snyk-test -f Dockerfile .

      - name: Perform Snyk Check (Docker)
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: fdp:snyk-test
          args: --severity-threshold=high
